-- Version-controls the Ancestral Roots and Energy & Bodywork Practice Branch
-- content. This data existed only as live rows in the production Supabase
-- project (seeded directly, never through a migration) -- a fresh database
-- rebuilt from this repo's migrations alone would have shown both branches
-- as published but with zero modules. Idempotent: safe to re-run against
-- the project that already has this data (ON CONFLICT upserts by slug/id).

INSERT INTO training_branches (id, slug, title, subtitle, description, sort_order, is_published, metadata) VALUES ('a86dd097-d791-49f7-9277-637919341a56', 'ancestral-roots', 'Ancestral Roots', 'Lineage Healing · Reconnection · Ancestral Wisdom', 'A 15-module experiential training branch built from the ASCEND Ancestral Roots facilitator curriculum. Practice, repetition, observation, integration and reflection take priority over passive reading.', '1', 't', '{"format": "training_branch", "source": "Ancestral Roots Facilitator Manual", "modules": 15}'::jsonb) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sort_order=EXCLUDED.sort_order, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branches (id, slug, title, subtitle, description, sort_order, is_published, metadata) VALUES ('31f144d6-7c9b-4fa0-b066-51594c4ae349', 'energy-bodywork', 'Energy & Bodywork', 'Energy Massage Practitioner Training', 'A progressive practitioner branch based on the ASCEND Energy Massage Practitioner’s Manual: practitioner state, energetic assessment, chakra harmonization, nadi balancing, Kundalini integration, zodiac correspondences, five-element work, spiritual techniques, and complete treatment protocols.', '2', 't', '{"format": "training_branch", "source": "Energy Massage Practitioner’s Manual", "modules": 11, "source_author": "ASCEND", "training_expansion": true, "recommended_prerequisite": "Core foundations before advanced energetic work"}'::jsonb) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sort_order=EXCLUDED.sort_order, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('8d4371b0-4754-44ef-807b-4b9d530ea838', 'a86dd097-d791-49f7-9277-637919341a56', '1', '1', 'Establishing the Ancestral Field', 'Entering the Tree', 'Establish the ancestral tree as the recurring inner landscape and begin mapping strength and disconnection.', '["Establishing connection", "Meeting the ancestral tree", "Roots and branches", "Strength and disconnection"]'::jsonb, 'A living relationship with the ancestral landscape and clearer lineage orientation.', '**Opening & Grounding:** Find a comfortable seated or lying position. Allow your eyes to close, or soften your gaze toward the floor. Take three slow, deep breaths, letting each exhale settle you more fully into the support beneath you. Feel the weight of your body grounded by gravity, supported by the earth.

**Induction:** Imagine a single point of light at the base of your spine. With your next breath, let this light extend downward as a root, moving through the floor, through soil and stone, deep into the body of the earth. Feel this root anchor you, drawing a quiet stability up into your body with each breath.

**Core Journey:** As you settle into this rootedness, sense a vast tree taking shape around and behind you — your ancestral tree. Its trunk rises through time itself; its branches reach backward through generations you may never have met, yet whose lives shaped the one you now live. Without forcing or searching, simply notice what arises. You might sense warmth in some branches and a thinning, quieter quality in others. You might feel pulled toward a particular direction — maternal, paternal, distant, near. There is no right experience here; trust whatever arises, however subtle.

Allow yourself to walk, in your inner vision, along one root or branch that draws your attention. Notice texture, color, temperature, or feeling. If a sense of disconnection appears, simply acknowledge it without needing to repair it today — you are only mapping the terrain.

**Integration:** When you feel ready, return your attention to the trunk, the central, unifying point of this tree. Place a hand over your heart and silently acknowledge: ‘I see you. I am here.’ Let this be received by the tree, however that registers for you — a softening, a stillness, a sense of being met.

**Closing & Return:** Slowly bring your awareness back to the root beneath your spine, and feel it gently retract, leaving a thread of connection in its place. Wiggle your fingers and toes. Take a deeper breath, and when ready, open your eyes. Take a few minutes to journal anything you noticed — an image, a feeling, a direction that called to you — without analyzing it yet.', '3–5 minutes of grounding and root establishment.', 'Notice family associations, learned responses or inherited narratives during ordinary life without deciding what they mean.', 'What did I notice? What remained uncertain?', 'Repeat the journey before reviewing the prior journal entry; compare what remained stable and what changed.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('43bb8cd2-f4c1-4484-b4fa-d8ce9486d4ff', 'a86dd097-d791-49f7-9277-637919341a56', '2', '1', 'Establishing the Ancestral Field', 'Healing the Mother’s Line', 'Explore maternal inheritance, emotional patterns, burdens, resilience and available strengths.', '["Maternal lineage", "Feminine inheritance", "Emotional patterns", "Inherited burdens", "Feminine wisdom"]'::jsonb, 'Greater emotional clarity, self-understanding and connection to the maternal ancestral stream.', '**Opening & Grounding:** Settle into stillness. Breathe deeply, allowing your body to soften with each exhale. Place one hand gently on your lower belly, the seat of receiving and nurturing. Breathe into this space.

**Induction:** Sense the root from your previous practice, or create it now — a line of connection from your spine into the earth. From this rootedness, turn your inner attention to the maternal branch of your ancestral tree — your mother, and her mother, and all the women whose lives converge in you.

**Core Journey:** See or sense your mother as a young woman, before the weight of any role she carried for you. Behind her, sense her mother, and behind that woman, another, the line continuing back further than memory can reach. Notice what travels along this line — perhaps resilience, perhaps grief carried quietly, perhaps fierce love, perhaps silence. Let whatever arises simply be present, without needing to fix or judge it.

If it feels supportive, ask inwardly: ‘What strength lives in this line that I carry?’ Wait without forcing an answer. An image, word, sensation, or simply a felt knowing may surface. Trust whatever comes, even if it seems small.

**Integration:** Bring a hand to your heart and offer gratitude to this maternal line — for the survival, the care, the sacrifices that allowed your own life to exist. If there is grief here too, let it be witnessed rather than carried forward unconsciously. You might silently say: ‘I receive your strength. I release what is not mine to carry.’

**Closing & Return:** Take a breath that reaches into your belly, and let your attention return fully to the room around you. Move your shoulders, open your eyes. When ready, write down any images, sensations, or words that arose, especially anything related to emotional patterns you recognize in yourself.', 'Brief maternal-line grounding using the established root.', 'Observe maternal-family patterns and strengths as they appear in daily life.', 'What seemed directly observed, remembered, interpreted or symbolically experienced?', 'Name one maternal strength to embody deliberately in ordinary life.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('714650ef-1b03-4c66-9377-7cd3862d9601', 'a86dd097-d791-49f7-9277-637919341a56', '3', '1', 'Establishing the Ancestral Field', 'Healing the Father’s Line', 'Explore paternal inheritance through confidence, direction, responsibility, purpose and personal power.', '["Paternal lineage", "Fathers and grandfathers", "Confidence", "Purpose", "Ancestral support"]'::jsonb, 'Greater grounding, direction, resilience and connection to the paternal ancestral stream.', '**Opening & Grounding:** Find your seat. Breathe slowly, lengthening the exhale. Notice the structure of your own spine, the way it holds you upright — an echo of the support you are about to explore.

**Induction:** Re-establish your root into the earth. From this stable base, turn your inner attention to the paternal branch of your ancestral tree — your father and his father, and the unbroken line of men who carried responsibility, direction, and purpose before you.

**Core Journey:** See or sense your father as a young man, perhaps as a boy, before any role he later carried. Behind him, sense his father, and further back, the line continuing into names and faces you may never know. Notice what travels here — confidence, burden, ambition, silence, protectiveness, unresolved striving. Whatever you find, simply witness it.

Ask inwardly, if it feels right: ‘What strength lives in this line that supports my own direction?’ Allow an answer to arise in its own form — an image, a posture, a single word.

**Integration:** Place a hand over your sternum, the center of your will, and acknowledge this line: ‘I receive your strength. I stand on what you built.’ If there is tension or unresolved weight here, simply notice it without needing to resolve it in this sitting.

**Closing & Return:** Let the root beneath you settle into stillness. Bring movement back into your hands and feet. Open your eyes slowly. Journal anything that surfaced, particularly around confidence, direction, or your relationship to authority and achievement.', 'Brief paternal-line grounding with attention to posture and spine.', 'Observe reactions involving authority, direction, responsibility or achievement.', 'What belongs to direct experience, family knowledge and my interpretation?', 'Choose one paternal strength and apply it consciously to one real situation.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('1ce3aaef-3baf-4df7-8e28-c41e5dae36d0', 'a86dd097-d791-49f7-9277-637919341a56', '4', '2', 'Differentiation & Release', 'Releasing What No Longer Belongs to You', 'Identify inherited beliefs, emotional patterns, expectations and roles, then practice differentiation and release.', '["Inherited patterns", "Limiting beliefs", "Family roles", "Generational cycles", "Personal growth"]'::jsonb, 'Greater clarity and freedom in relation to inherited patterns.', '**Opening & Grounding:** Settle into your seat, spine long but relaxed. Breathe in fully, and exhale with a slight sigh, releasing tension from your jaw and shoulders.

**Induction:** Reconnect with your root into the earth. This time, imagine the earth itself as a place that transforms what is given to it — composting, breaking down, renewing. You are not discarding into a void; you are returning to a place that knows how to transform.

**Core Journey:** Bring to mind a pattern you suspect is not fully your own — a fear, a belief, a way of responding that feels older than your own experience. Without forcing detail, simply sense its shape. Ask inwardly: ‘Where did this begin?’ You may sense a face, a generation, a feeling of inheritance. You don’t need certainty — an impression is enough.

Visualize this pattern as an object, a cloak, a stone, a thread — whatever form it takes. Notice that you can hold it at a slight distance from your body, observing it rather than being fused with it.

**Integration:** Speak inwardly: ‘I honor where this came from. I release what is no longer mine to carry.’ Imagine releasing the object into the earth through your root, watching it dissolve, transform, or simply leave your felt sense of self. Notice the space that remains where the pattern once sat.

**Closing & Return:** Breathe into that newly opened space, allowing it to fill with your own breath rather than rushing to fill it with something else. Slowly bring movement back to your body, and open your eyes. Journal what pattern you released and what, if anything, arose in the space it left.', 'Name one recurring pattern and observe it at a slight distance for several breaths.', 'Log trigger → automatic response → possible inherited pattern → conscious alternative.', 'What do I know, what do I suspect, and what remains uncertain?', 'Practice one conscious alternative response in daily life.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('fc5ddccd-580d-4153-ab55-e40af1724094', 'a86dd097-d791-49f7-9277-637919341a56', '5', '2', 'Differentiation & Release', 'Ancestral Gifts & Blessings', 'Shift from inherited difficulty toward strengths, talents, resilience, creativity and wisdom.', '["Ancestral strengths", "Talents", "Resilience", "Family wisdom", "Supportive inheritance"]'::jsonb, 'Deeper appreciation of lineage resources and confidence in natural abilities.', '**Opening & Grounding:** Settle comfortably, and take a few breaths simply noticing the support beneath you, without needing to change anything yet.

**Induction:** Establish your root into the earth, and this time, invite a sense of warmth to travel down through it, like sunlight reaching into soil.

**Core Journey:** Turn your attention to your ancestral tree as a whole, and ask inwardly: ‘What gift lives within this lineage that I have not fully claimed?’ Let the question rest gently rather than searching urgently. A talent, a way of seeing, a resilience, a form of creativity, a kind of humor or warmth may surface from any branch of the tree.

If nothing arises immediately, simply walk your inner gaze along the branches, noticing where warmth or brightness seems to gather. Trust the first impression, even if it feels ordinary.

**Integration:** When something arises, receive it consciously. Imagine drawing this gift gently into your own body, perhaps into your hands, your chest, or your mind. Acknowledge it: ‘This already lives in me. I welcome it more fully.’

**Closing & Return:** Take a full breath, feeling this gift settle into your body. Bring your attention back into the room, and when ready, open your eyes. Write down the gift you received and one way you might let it live more visibly in your daily life.', 'Recall and embody one lineage strength for 3 minutes.', 'Use one identified strength deliberately during the day.', 'How did the quality change when expressed through action?', 'Record evidence of the quality in behavior rather than only imagery.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('adf9dcd4-0d4e-47a2-bcba-708becd5f1b0', 'a86dd097-d791-49f7-9277-637919341a56', '6', '2', 'Differentiation & Release', 'The Wisdom Keepers', 'Explore lineage figures associated with wisdom, courage, healing or guidance without forcing interpretation.', '["Ancestral wisdom", "Guiding figures", "Family teachings", "Inner guidance", "Connection"]'::jsonb, 'A greater sense of guidance, support and connection to lineage wisdom.', '**Opening & Grounding:** Settle into stillness, breathing naturally, allowing your body to find its own quiet rhythm.

**Induction:** Re-establish your root, and this time imagine it extending not just downward, but backward through time, like a thread leading deep into your family’s history.

**Core Journey:** Sense, somewhere along this thread, the presence of a wisdom keeper — a figure within your lineage who carried insight, healing ability, courage, or guidance. You may not know their name or even their exact place in the family; trust whoever or whatever presents itself, even if it appears symbolically rather than as a literal person.

Approach this presence with respect rather than urgency. If it feels welcoming, ask: ‘What do you want me to know?’ Wait without expectation. The answer may come as a word, an image, a feeling, or simply a shift in your body.

**Integration:** Receive whatever comes, even if it is subtle or seems incomplete. Offer thanks inwardly, regardless of the form your experience took. Trust that contact, however faint, has value.

**Closing & Return:** Let the thread of connection soften without fully disappearing — you can return to it again. Bring your awareness back into your body and the room around you. When ready, open your eyes and record what you received, including any impressions that felt important even if you cannot explain why.', 'Sit with one received word/image without interpreting it for several minutes.', 'Notice whether the same theme appears naturally in ordinary life.', 'What was experienced, and what meaning did I add afterward?', 'Return to the same question on another day and compare experiences.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('34736f25-d869-4fa3-84ce-e0530c1f5cd5', 'a86dd097-d791-49f7-9277-637919341a56', '7', '3', 'Deeper Lineage Structures', 'Deep Roots', 'Move beneath individual stories toward continuity, rootedness and belonging.', '["Deep roots", "Continuity", "Inherited strengths", "Belonging"]'::jsonb, 'A deeper experience of rootedness, connection and perspective.', '**Opening & Grounding:** Settle into a posture that feels stable and supported. Take several slow breaths, allowing each one to draw you deeper into stillness.

**Induction:** Establish your root as before, but this time, follow it further than you have previously gone — past individual ancestors, past names and faces, into a depth where the roots become less personal and more elemental, like a current beneath the family stories.

**Core Journey:** Notice that beneath the specific stories of your maternal and paternal lines lies a shared ground — a deeper layer where all the branches of your tree converge into something more fundamental: simply life continuing, generation after generation, seeking to express itself through you. Rest in this deeper layer without needing to interpret it. Let it simply hold you.

If an image arises — bedrock, water, light, simply darkness and presence — allow it to remain rather than trying to make meaning of it immediately.

**Integration:** Notice how this depth feels in your body — perhaps a settling in your low belly, a steadiness in your spine, or simply quiet. Acknowledge silently: ‘I belong to something larger than any single story.’

**Closing & Return:** Slowly allow the depth to recede, while keeping a felt sense of having touched it. Bring movement back to your fingers and toes, and open your eyes when ready. Take a few minutes before journaling — this experience may resist words more than others.', 'Five-minute root-and-spine settling practice.', 'Notice moments of belonging and separation without immediately explaining them.', 'Where did rootedness register in my body and behavior?', 'Repeat the deeper-root journey and note stable versus changing elements.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('9da4f46d-248d-4acc-9c2b-fb43f8550749', 'a86dd097-d791-49f7-9277-637919341a56', '8', '3', 'Deeper Lineage Structures', 'Family Patterns & Invisible Loyalties', 'Train awareness of repeating family patterns, expectations, roles and the possibility of conscious choice.', '["Repeating patterns", "Inherited expectations", "Family roles", "Invisible loyalties", "Choice"]'::jsonb, 'Greater awareness of inherited influences and increased freedom to choose consciously.', '**Opening & Grounding:** Find your seat, and let your breath settle into an even, unhurried rhythm.

**Induction:** Reconnect with your root into the earth. As you settle, invite a sense of clear, gentle awareness — you are here to observe, not to judge.

**Core Journey:** Bring to mind a recurring pattern in your life — a relationship dynamic, a recurring struggle, an automatic reaction. Ask inwardly: ‘Whose pattern is this, originally?’ Without needing proof, notice if an ancestor, a role, or a family expectation comes to mind.

Sense whether this pattern feels like loyalty — a way of staying connected to your family by continuing something, even unconsciously. If so, acknowledge this loyalty with respect rather than criticism: it likely formed to protect or preserve something important at the time.

**Integration:** Speak inwardly: ‘I see this loyalty. I choose how I carry it forward.’ You do not need to decide anything definitive in this moment — simply notice that choice exists where before there may have only seemed to be repetition.

**Closing & Return:** Take a breath that affirms your own presence in this moment, separate from the pattern you just witnessed. Bring your attention back to the room, and open your eyes. Journal the pattern you identified and any sense of choice that emerged.', 'Pause at one automatic reaction and name the pattern before acting.', 'Keep a pattern log: trigger → response → family association → conscious choice.', 'Where did choice become possible where repetition had felt automatic?', 'Practice one alternative response repeatedly during the integration period.', '3', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('d99c6562-05a1-4318-8562-df498182aea0', 'a86dd097-d791-49f7-9277-637919341a56', '9', '4', 'Maternal & Paternal Integration', 'Healing the Mother Wound', 'Explore the maternal relationship and its possible imprint on love, safety, nurturing, emotional expression and self-worth.', '["Relationship with mother", "Emotional nourishment", "Self-worth", "Receiving support", "Integration"]'::jsonb, 'Greater emotional balance, self-compassion and inner stability.', '**Opening & Grounding:** Settle gently, and place a hand on your heart. Take a few breaths, allowing your body to feel supported by the surface beneath you.

**Induction:** Establish your root, and this time also imagine a soft light surrounding your body, like a boundary of care as you do this work.

**Core Journey:** Bring to mind your relationship with your mother, beginning gently with whatever feels safe to approach today — perhaps a single memory, a felt sense, or simply the general quality of the relationship. Notice where in your body this relationship lives — perhaps your chest, your throat, your stomach.

If a younger version of yourself appears in your inner vision, offer them attention rather than analysis. You might silently say to that younger self: ‘I see you. You were doing your best to be loved.’ Let this be tender rather than demanding.

**Integration:** If it feels appropriate, imagine offering yourself now the nurturing or acknowledgment that younger self needed. This does not require changing the past — only offering presence to it now. Breathe into your chest and let any emotion move without needing to suppress or amplify it.

**Closing & Return:** When ready, let the soft light around you brighten gently, and bring your awareness fully back into the room. Open your eyes slowly. This work can bring up real feeling — be gentle with yourself afterward, and consider resting or speaking with someone you trust if anything intense surfaced.', 'Grounding plus a clear stop/return cue before entering the journey.', 'No required field assignment immediately afterward; prioritize settling and ordinary routine.', 'What arose, what do I need now, and what should remain unresolved for the moment?', 'Complete a delayed integration reflection rather than immediately beginning another intensive practice.', '1', 'enhanced', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('3d0fbfa2-3601-4fac-bf0f-430eaaa21948', 'a86dd097-d791-49f7-9277-637919341a56', '10', '4', 'Maternal & Paternal Integration', 'Healing the Father Wound', 'Explore the paternal relationship and themes of confidence, authority, boundaries, achievement and direction.', '["Relationship with father", "Confidence", "Authority and boundaries", "Direction", "Resilience"]'::jsonb, 'Greater self-trust, confidence and personal empowerment.', '**Opening & Grounding:** Settle into your seat, feeling the ground beneath you as a steady support. Take a few calming breaths.

**Induction:** Establish your root and surround yourself with the same protective light as before, creating a felt sense of safety for this work.

**Core Journey:** Bring to mind your relationship with your father, approaching whatever feels accessible today — an image, a memory, or simply a general quality. Notice where this relationship registers in your body — perhaps your jaw, your shoulders, your gut.

If it feels right, allow a younger version of yourself to appear. Offer them attention: ‘I see you. You were doing your best to find your strength.’ Let this be received without forcing resolution.

**Integration:** If appropriate, imagine offering that younger self the support, encouragement, or boundary they needed. Breathe into your lower back and shoulders, the seat of standing tall, and let any tension begin to soften.

**Closing & Return:** Allow the protective light to brighten as you complete this journey. Bring your awareness back into your body and the room. Open your eyes gently. As with the previous workshop, this material can be tender — give yourself time before re-entering ordinary activity.', 'Grounding plus a clear stop/return cue before entering the journey.', 'No required field assignment immediately afterward; prioritize settling and ordinary routine.', 'What arose, what do I need now, and what should remain unresolved for the moment?', 'Complete a delayed integration reflection and return only when sufficiently settled.', '1', 'enhanced', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('25e7fafb-d504-40c0-aa6f-7d7c9c247d6c', 'a86dd097-d791-49f7-9277-637919341a56', '11', '5', 'Recovering Ancestral Resources', 'Ancestors of Strength', 'Reconnect with endurance, courage, adaptability and resilience as lineage resources.', '["Resilience", "Family strengths", "Courage", "Adaptability", "Inner resources"]'::jsonb, 'A stronger sense of resilience, confidence and personal capability.', '**Opening & Grounding:** Settle into your seat. Take three breaths, each one a little fuller than the last.

**Induction:** Establish your root, and this time invite a sense of solidity to rise up through it — like stone, like deep-rooted trees that have weathered many storms.

**Core Journey:** Ask your ancestral tree: ‘Show me one who endured.’ Allow an image, a feeling, or simply a sense of presence to arise — someone, named or unnamed, who faced hardship and continued forward. Notice how their resilience feels in your body as you sense them.

You might silently ask: ‘What carried you through?’ and listen for whatever response — a word, an image, a quality — surfaces.

**Integration:** Acknowledge this ancestor: ‘Your endurance lives in me.’ Notice if a particular part of your body feels strengthened or steadied by this contact — perhaps your spine, your legs, your hands.

**Closing & Return:** Let this sense of solidity settle into your body as a resource you can return to. Bring movement back to your fingers and toes, and open your eyes when ready. Journal what or who you encountered, and where you felt their strength in your body.', 'Evoke one identified strength and locate its bodily expression.', 'Apply that quality to one ordinary challenge.', 'What changed when the quality became action rather than an idea?', 'Repeat: identify → evoke → embody → apply → record.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('4c27cf2e-fb9b-493d-92f1-d6e3689edf39', 'a86dd097-d791-49f7-9277-637919341a56', '12', '5', 'Recovering Ancestral Resources', 'Ancestors of Wisdom', 'Explore accumulated lessons, values and perspectives carried through the family tree.', '["Family wisdom", "Life lessons", "Values", "Guidance", "Inner knowing"]'::jsonb, 'A deeper connection to personal wisdom and inner guidance.', '**Opening & Grounding:** Settle comfortably, breathing slowly and evenly.

**Induction:** Re-establish your root, and this time invite a sense of spaciousness above you, as if your crown opens gently toward something larger.

**Core Journey:** Ask your ancestral tree: ‘What wisdom have you accumulated that wants to reach me now?’ Rather than seeking a single figure, allow the question to be held by the whole lineage. Notice what arises — a phrase, an image, a value, a simple knowing.

If specific guidance emerges, let it arrive without immediately analyzing or applying it. Simply receive.

**Integration:** Place both hands over your heart and acknowledge what you received: ‘I carry this wisdom forward.’ Let yourself feel the weight, or lightness, of this transmission.

**Closing & Return:** Slowly let the spaciousness above you settle, and bring your awareness fully into your body. Open your eyes when ready. Record the wisdom you received, even if it seems simple — simple wisdom is often the most enduring.', 'Hold one received value or phrase in quiet attention.', 'Test the value through one concrete choice in ordinary life.', 'What did practice reveal that contemplation alone did not?', 'Record what remained useful after practical application.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('432d8f9c-1143-4550-9ae0-29d30e0bf5d9', 'a86dd097-d791-49f7-9277-637919341a56', '13', '5', 'Recovering Ancestral Resources', 'Belonging', 'Explore ancestry in relation to family, community, culture, continuity and one’s place within a larger story.', '["Identity", "Family connection", "Community", "Acceptance", "Roots"]'::jsonb, 'A stronger sense of connection, belonging and rootedness.', '**Opening & Grounding:** Find your seat, and take a breath that settles your whole body.

**Induction:** Establish your root, and this time sense the wider field around your tree — the community, the culture, the land your ancestors moved through.

**Core Journey:** Allow yourself to sense your place within this larger story — not as separate from it, but as a living continuation of it. Notice any places where you feel separation: from family, from culture, from yourself. Simply observe these without needing to immediately resolve them.

Ask inwardly: ‘Where do I already belong, even if I have not fully recognized it?’ Let an answer surface gently — it may be a place, a person, a quality, or simply a feeling of being held.

**Integration:** Breathe into whatever sense of belonging arose, allowing it to expand slightly with each breath. Acknowledge: ‘I am part of this story, and this story is part of me.’

**Closing & Return:** Let your awareness widen to include the room around you. Bring movement back into your body, and open your eyes. Journal where you noticed separation and where you noticed belonging.', 'Brief grounding while sensing both body and surrounding environment.', 'Notice three moments of connection or separation during ordinary life.', 'Where did belonging become observable rather than conceptual?', 'Choose one grounded act of connection consistent with the experience.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('6c89d8a3-990d-4578-9447-8dc6a358f2ac', 'a86dd097-d791-49f7-9277-637919341a56', '14', '6', 'Direction & Legacy', 'Ancestors & Life Purpose', 'Explore how inherited strengths and gifts may support personal direction and meaningful contribution.', '["Life direction", "Inherited strengths", "Personal gifts", "Contribution", "Purpose"]'::jsonb, 'Greater clarity regarding personal direction and meaningful contribution.', '**Opening & Grounding:** Settle into a position that feels stable and open. Breathe naturally.

**Induction:** Establish your root, and imagine a line extending not only backward into your ancestry, but also forward, into your own unfolding path.

**Core Journey:** Ask your ancestral tree: ‘What strength or gift have I inherited that wants to be expressed through my life’s direction?’ Allow whatever arises — a talent, a quality, a way of relating to others — to surface without forcing it into a specific career or role.

Notice how this gift might already be present in small ways in your current life, even if not yet fully expressed.

**Integration:** Acknowledge inwardly: ‘This gift is mine to carry forward.’ Let yourself imagine, briefly, one small way you could express this gift more fully in the coming weeks.

**Closing & Return:** Bring your awareness back into your body and the room around you. Open your eyes when ready. Journal the gift you identified and the small step that came to mind.', 'Recall one identified gift and imagine one modest expression of it.', 'Take one small real-world action expressing the quality without forcing it into a predetermined role or career.', 'What happened when I expressed the quality concretely?', 'Review action-based evidence and choose the next small expression.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('9f8ebbb1-cd93-4a7e-8748-581ca7097e18', 'a86dd097-d791-49f7-9277-637919341a56', '15', '6', 'Direction & Legacy', 'Legacy: What Will You Pass Forward?', 'Turn the branch forward: consciously choose values, strengths and qualities to carry onward rather than unconsciously repeat.', '["Legacy", "Values", "Future generations", "Conscious living", "Present choices"]'::jsonb, 'A deeper understanding of one’s role within the continuing family story.', '**Opening & Grounding:** Settle into your seat, breathing slowly, allowing your body to feel both grounded and present.

**Induction:** Establish your root, and this time sense it extending forward as well — toward those who will come after you, known or unknown.

**Core Journey:** Ask yourself: ‘What do I want to consciously pass forward, rather than unconsciously repeat?’ Allow images or qualities to surface — values, strengths, ways of loving, ways of facing difficulty. Notice the difference between what you received and what you now choose to carry forward intentionally.

If it feels helpful, imagine someone in the future — a descendant, a person you will influence, even symbolically — receiving this gift from you.

**Integration:** Speak inwardly: ‘This is what I choose to carry forward.’ Let this intention settle into your body as something real and chosen, rather than simply assumed.

**Closing & Return:** Slowly bring your awareness back into the room. Open your eyes when ready. Journal your chosen legacy, and consider sharing it with the group if you feel called to.', 'Quietly name what you choose to carry forward and what you choose not to repeat.', 'Express one chosen legacy value through a concrete action or relationship.', 'What do I consciously pass forward rather than unconsciously repeat?', 'Create a persistent Legacy statement and revisit it after the branch is complete.', '2', 'standard', 't', '{"source": "Ancestral Roots Facilitator Manual", "canonical": true, "expansion": "ASCEND training design", "source_file": "Ancestral_Roots_Facilitator_Manual.docx", "library_file_id": "libfile_a93f93844784819190d7ed56b8dc6925"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('1802e352-2293-4fd0-b1b7-2c50d4de2d5c', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '1', '1', 'Foundations', 'Practitioner State & Session Foundation', 'Energy massage restores the natural circulation of vital energy through the body as a unified whole, rather than treating isolated symptoms — every technique that follows depends on the practitioner state and session structure this module establishes.', '["calm breathing", "stable posture", "relaxed hands and shoulders", "continuous concentration", "deliberate session sequence"]'::jsonb, 'A stable, repeatable session structure and a practitioner state calm and focused enough to sustain it.', 'Energy massage is a system of manual and energetic techniques intended to restore the natural circulation of vital energy throughout the human body. Rather than treating isolated symptoms, the practitioner works with the body''s energetic structure as a unified whole. The objective of each session is to identify disturbances in energetic circulation, remove stagnation where possible, strengthen weakened areas, and restore harmony between the physical body and its subtle energy systems. Treatment is performed deliberately and systematically — every movement should have a clear purpose and be supported by concentration, awareness, and steady intention. View every treatment as restoration of energetic equilibrium, not simply relief of discomfort.

The Role of the Practitioner: you serve as a guide for energetic correction, not a source of force. During treatment, maintain calm breathing, stable posture, continuous concentration, relaxed shoulders and hands, an even emotional state, and focused intention — distraction weakens the effectiveness of energetic work.

Preparing the Environment: ensure the room is quiet, remove unnecessary distractions, maintain a comfortable temperature, prepare a stable treatment surface, and allow sufficient uninterrupted time. The environment should encourage relaxation for both practitioner and client.

Preparing Yourself: before every session, calm the mind, relax the body, warm the hands, regulate your breathing, focus attention, and release emotional tension. Your internal state directly influences the quality of treatment.

Preparing the Client: the client should lie comfortably, relax completely, breathe naturally, remove restrictive clothing or accessories, and remain still unless instructed otherwise. Before beginning, explain the treatment sequence so they understand the process.

General Principles: treatment should always be calm, consistent, balanced, progressive, and deliberate. Movements should not be rushed; pressure should remain appropriate to the technique; attention should stay on energetic flow rather than mechanical manipulation alone.

Sequence of a Session: preparation, initial energetic assessment, identification of energetic imbalance, primary treatment, harmonization, final assessment, completion. Maintaining a consistent sequence helps create stable treatment results.

Closing the Session: at the conclusion, reassess energetic balance, allow the client several minutes to rest, encourage slow movement when standing, and record observations for future sessions. A session concludes only after energetic balance has been re-evaluated, before the client leaves.', 'Before any hands-on work, run through the full session sequence once in your mind: preparation, initial assessment, identifying imbalance, primary treatment, harmonization, final assessment, completion — so the structure is automatic rather than something to think through mid-session.', 'Prepare a client for a real or practice session: explain the treatment sequence in plain language, help them settle into a comfortable, relaxed position, and confirm they have removed anything restrictive before you begin.', 'Where did your own internal state, calm or scattered, focused or distracted, visibly affect the quality of a session you gave or received?', 'This module''s practitioner-state and session-structure work underlies every module that follows; return to it whenever a later technique feels rushed or mechanical rather than deliberate.', '3', 'standard', 't', '{"source_basis": "manual", "source_chapters": [1, 2, 3], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('ae6ea945-3664-481e-ad92-0c6e70175c45', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '2', '2', 'Energetic Assessment', 'Assessment, Spine & Treatment Priority', 'Diagnosis always precedes correction. This module builds the observational skill, visual, tactile, and energetic, needed to determine where and how to treat before any hands-on correction begins.', '["general observation", "energetic perception", "spinal assessment", "chakra assessment", "treatment priority", "record keeping"]'::jsonb, 'A reliable diagnostic pass that identifies primary and secondary imbalances and produces a clear, recorded treatment priority before any correction begins.', 'Energetic diagnosis is performed before every treatment. Its purpose is to determine the condition of the client''s energetic system, identify areas of stagnation or deficiency, and establish the order of treatment. Diagnosis always precedes correction.

General Assessment: before physical contact, observe the client — general posture, breathing pattern, body symmetry, areas of visible tension, ease of movement, and overall vitality. Visual observation provides the first impression of energetic balance.

Establishing Contact: before beginning diagnosis, relax your hands, calm your breathing, focus your attention, place your hands gently without applying pressure, and allow several moments to perceive the energetic state. Avoid rushing the assessment.

Palpation: using relaxed hands, examine the body systematically. Look for areas of excessive tension, regions lacking energetic responsiveness, differences between the left and right sides, localized discomfort, variations in temperature, and changes in tissue density. These findings help determine where treatment should begin.

Energetic Perception: during examination, remain attentive to what you perceive through the hands — strong energetic flow, weak energetic flow, interrupted circulation, local stagnation, uneven distribution, and areas requiring further attention. Record these observations mentally before treatment.

Examination of the Spine: the spinal column serves as the central axis for many energetic relationships. Proceed from the upper cervical region downward, examining each section carefully. Observe tender areas, muscle tension, restricted movement, areas of energetic congestion, and regions of reduced sensitivity. The spine provides important information about overall energetic balance.

Assessment of the Chakras: examine each primary energy center individually. Assess relative activity, balance with neighboring centers, strength of energetic response, areas of congestion, and areas of weakness. Do not attempt correction during diagnosis — the purpose at this stage is observation only.

Determining Treatment Priority: after completing examination, identify the primary energetic disturbance, secondary areas requiring correction, regions that should not be treated immediately, and the most appropriate treatment sequence. Treatment should progress from major imbalance toward finer correction.

Recording Findings: note the general energetic condition, significant areas of imbalance, response during examination, planned treatment approach, and findings to compare during future sessions. Consistent records make it possible to evaluate progress over multiple treatments.', 'Spend a full minute in visual observation alone before ever touching a client — resist the pull to start diagnosing through touch before you have completed looking.', 'Examine the spine from the upper cervical region downward, noting tender areas, muscle tension, restricted movement, congestion, and reduced sensitivity — record findings without attempting any correction during this pass.', 'What did you notice through observation alone that touch later confirmed, or that touch revealed you had missed?', 'The treatment priority you establish here, primary disturbance, secondary areas, regions to leave alone for now, determines the order everything in the chakra, nadi, and kundalini modules ahead will actually be applied in.', '3', 'standard', 't', '{"source_basis": "manual", "source_chapters": [4, 5], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('0ef2f075-29b1-4c74-9195-52c7057bb383', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '3', '3', 'Chakra Massage', 'Seven Primary Chakras', 'Chakra massage restores balance across the body''s seven primary energy centers, treated systematically in ascending order from Root to Crown, since disturbance in one center can affect the whole system.', '["Root", "Sacral", "Solar Plexus", "Heart", "Throat", "Third Eye", "Crown"]'::jsonb, 'The ability to locate, assess, and treat each of the seven primary chakras individually, with a clear sense of each center''s distinct purpose.', 'Chakra massage is intended to restore balance within the body''s primary energy centers. Each chakra influences specific physical, emotional, and energetic functions. Disturbance in one center may affect the entire energetic system, so treatment is performed systematically rather than focusing only on a single area. The objective is a balanced flow of energy through all seven primary chakras, treated in ascending order.

Root Chakra (Muladhara) — Location: base of the spine. Function: stability, grounding, survival, and physical vitality. Purpose of treatment: restore grounding, improve energetic stability, strengthen the lower energetic foundation, and encourage balanced energy circulation.

Sacral Chakra (Svadhisthana) — Location: lower abdomen. Function: vitality, creativity, and emotional expression. Purpose of treatment: restore energetic movement, improve fluidity, and harmonize emotional energy.

Solar Plexus Chakra (Manipura) — Location: upper abdomen. Function: personal strength, willpower, and energetic distribution. Purpose of treatment: strengthen energetic activity, balance personal energy, and remove stagnation.

Heart Chakra (Anahata) — Location: center of the chest. Function: balance, compassion, and energetic integration. Purpose of treatment: restore harmony, improve energetic circulation between upper and lower centers, and encourage balanced flow.

Throat Chakra (Vishuddha) — Location: throat. Function: communication and energetic expression. Purpose of treatment: reduce energetic restriction, restore balanced expression, and improve upward energetic movement.

Third Eye Chakra (Ajna) — Location: center of the forehead. Function: perception, awareness, and mental clarity. Purpose of treatment: improve energetic focus, harmonize mental activity, and support intuitive perception.

Crown Chakra (Sahasrara) — Location: top of the head. Function: higher consciousness and integration of the energetic system. Purpose of treatment: complete energetic harmonization, encourage balanced circulation through the entire system, and integrate the effects of treatment.', 'Before treating a single chakra, silently name its location and function to yourself, so intention is clear before the hands arrive.', 'Treat one chakra fully in a practice session, then pause and assess: has its relative activity and balance with neighboring centers actually shifted?', 'Which of the seven centers was hardest to sense clearly, and what did that difficulty itself tell you?', 'This module is the foundation the next module''s full-system harmonization builds on directly — do not proceed to harmonizing all seven together until each is individually familiar.', '3', 'standard', 't', '{"source_basis": "manual", "source_chapters": [6], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('1a37260a-2096-47d1-9fb3-12ff597ca514', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '4', '3', 'Chakra Massage', 'Complete Chakra Harmonization', 'Once each chakra can be treated individually, this module integrates them into one continuous harmonization, moving from Root to Crown and back to reassess the whole system together.', '["reassessment", "adjacent-center comparison", "remaining imbalance", "Root-to-Crown final harmonization"]'::jsonb, 'A complete, integrated chakra harmonization that leaves all seven centers in balanced relationship to each other, not just individually treated.', 'Before beginning, ensure the client is relaxed, confirm the findings from the energetic assessment, place the hands gently over the appropriate energetic center, and allow a brief period of stillness before beginning the technique. Maintain continuous concentration throughout the treatment.

After treating each chakra individually: reassess each center, compare energetic balance between adjacent chakras, and address any remaining imbalance. Then perform a final harmonization from the Root Chakra to the Crown Chakra.

Allow the client to rest quietly before continuing with advanced techniques. Once the chakras are balanced, treatment may progress to the central energetic channels — Sushumna, Ida, and Pingala — which form the next stage of the system.', 'After treating any two adjacent chakras, pause and compare them directly — which one still feels more active or more depleted than the other?', 'Complete one full Root-to-Crown harmonization pass in a session, then let the client rest quietly before continuing to any further technique.', 'What changed between your first pass through the seven centers and the final harmonization pass?', 'Only once the seven centers show balanced circulation together should treatment proceed to the central channels — Sushumna, Ida, and Pingala — covered next.', '3', 'standard', 't', '{"source_basis": "manual", "source_chapters": [7], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('0bcdf58f-b592-41d1-9fd8-1fbc53ee91a0', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '5', '4', 'Nadi Massage', 'Sushumna, Ida & Pingala', 'Three principal channels regulate the circulation of vital energy: Sushumna, the central channel; Ida, the lunar and receptive channel; and Pingala, the solar and active channel. This work only begins once the chakra system is already assessed and harmonized.', '["Sushumna central integration", "Ida receptive/cooling", "Pingala active/warming", "smooth controlled movement"]'::jsonb, 'Independent competence treating Sushumna, Ida, and Pingala, with a felt sense of each channel''s distinct quality.', 'Within the energetic body, three principal channels regulate the circulation of vital energy. Together they form the central energetic framework upon which advanced massage techniques are based: Sushumna, the central channel; Ida, the lunar channel; and Pingala, the solar channel. Before working with these channels, the chakra system should already have been assessed and harmonized.

Sushumna Nadi: regarded as the central pathway of energetic circulation. It extends along the body''s central axis and serves as the primary channel through which the energetic system is integrated. Treatment aims to restore central energetic balance, improve communication between the chakras, reduce energetic stagnation, and prepare the body for deeper energetic work. Begin only after the client has reached a relaxed state, and work progressively along the central axis, maintaining continuous concentration on the movement of energy. Movements remain smooth, continuous, symmetrical, and controlled — never hurried or forceful. A balanced Sushumna shows even energetic perception along the central axis, reduced congestion, a harmonious relationship between the upper and lower chakras, and a general sense of energetic stability.

Ida Nadi: represents the receptive, calming aspect of the energetic system. Treatment reduces energetic excess, encourages relaxation, balances emotional activity, and supports restorative processes. Follow the course of the channel carefully, pausing where imbalance is perceived, with attention on continuity of flow, even distribution, and gentle correction — excessive force is avoided. Afterward, the client may experience greater calmness, improved relaxation, reduced nervous tension, and a more balanced emotional state.

Pingala Nadi: represents the active and dynamic aspect of the energetic system. Treatment restores vitality and strengthens energetic circulation where deficiency is present. Proceed methodically while maintaining awareness of the relationship between Pingala and the central channel; movements remain deliberate, balanced, and continuous, avoiding overstimulation. Balanced Pingala activity may show as increased vitality, improved energetic responsiveness, better physical alertness, and stronger energetic circulation.', 'Before working either side channel, reconfirm Sushumna''s central balance — the side channels are worked in relation to a centered axis, not independently of it.', 'Treat Ida and Pingala in the same session and note, immediately afterward, which channel the client''s body seemed to respond to more readily.', 'How did the qualities of Ida (calming, receptive) and Pingala (active, dynamic) actually feel different under your hands, beyond their descriptions?', 'The three channels are assessed together before any comparison of balance is meaningful — this module''s individual channel work sets up the direct Ida-Pingala comparison in the next module.', '3', 'standard', 't', '{"source_basis": "manual", "source_chapters": [8], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('de3bf3fb-3f9f-406b-936d-ca2149a5e818', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '6', '4', 'Nadi Massage', 'Three-Channel Balance & Integration', 'With each channel treated individually, this module compares Ida and Pingala directly and integrates all three channels into one balanced system — the foundation Kundalini work depends on.', '["left-right comparison", "equilibrium", "three-channel harmonization", "reassessment"]'::jsonb, 'A fully integrated three-channel system, confirmed through direct comparison rather than assumed from individual treatment alone.', 'Balancing Ida and Pingala: following individual treatment of each channel, compare their relative energetic activity. The objective is not to strengthen one over the other but to establish equilibrium. Indicators of successful balancing include even energetic perception on both sides of the body, reduced asymmetry, a harmonious relationship with the chakra system, and stable energetic circulation.

Three-Channel Harmonization: the final stage integrates Sushumna, Ida, and Pingala. Reassess the entire energetic system before concluding this section of treatment. Only after the three primary channels demonstrate balanced circulation should work proceed to the next stage — Kundalini massage — where the integrated energetic system becomes the foundation for advanced practice.', 'Check for asymmetry between the left and right sides of the body specifically — this is the clearest physical signal of Ida-Pingala imbalance.', 'Only advance a client to three-channel harmonization once you can point to concrete signs of balance: even perception on both sides, reduced asymmetry, and a harmonious relationship with the already-balanced chakra system.', 'What told you the three channels were genuinely integrated, rather than just sequentially treated?', 'This module is an explicit gate — proceed to Kundalini work only after Sushumna, Ida, and Pingala together show stable, balanced circulation.', '3', 'standard', 't', '{"source_basis": "manual", "source_chapters": [9], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('1d6a9001-ff79-4d73-98f8-3b35882ca0ef', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '7', '5', 'Advanced Integration', 'Kundalini Integration', 'Kundalini massage is an advanced stage, performed only once assessment, chakra harmonization, and three-channel balancing are already complete. Its purpose is to support the harmonious movement of energy through the whole system while maintaining stability throughout.', '["prerequisite confirmation", "central energetic treatment", "chakra integration", "continuous reassessment", "stability"]'::jsonb, 'The ability to safely integrate Kundalini work into a session, with stability maintained throughout and confirmed at completion.', 'Kundalini massage is an advanced stage of energetic work, performed only after completing assessment, chakra harmonization, and balancing of the three primary nadis. The purpose of this stage is to support the harmonious movement of vital energy through the entire energetic system while maintaining balance and stability.

Purpose
Integrate the work completed on the chakras.
Strengthen the continuity of energetic circulation.
Improve coordination between the central channel and the energy centers.
Promote overall energetic harmony.
Support the body''s natural energetic equilibrium.

Prerequisites
Before beginning, confirm that the client is relaxed, energetic assessment has been completed, the chakras have been harmonized, Sushumna has been treated, Ida and Pingala are balanced, and no major energetic disturbances remain unresolved. Only after these conditions are met should the practitioner proceed.

Treatment Sequence
Preparation.
Confirmation of energetic balance.
Central energetic treatment.
Integration with the chakra system.
Reassessment of energetic flow.
Final harmonization.

During treatment, maintain calm concentration, work in a steady rhythm, avoid abrupt movements, observe the client''s energetic response throughout the session, and pause whenever reassessment is required. As treatment progresses, observe the relationship between the central energetic current and each chakra, maintaining continuous circulation, even energetic distribution, harmonious interaction between all primary energy centers, and stability throughout the system.

Completion
When treatment is complete: reassess the energetic system, confirm balanced circulation, allow the client to remain at rest, record significant observations, and recommend an appropriate interval before the next session if further treatment is indicated. The session concludes only after the practitioner is satisfied that the energetic system has reached a stable and balanced state.', 'Before beginning, run through the prerequisite checklist explicitly rather than from memory — this is the one stage where skipping a prerequisite carries real weight.', 'Complete a full Kundalini session only when every prerequisite genuinely holds, and record afterward whether the session revealed any prerequisite that was less solid than it appeared.', 'What signs would tell you a client was not actually ready for this stage, even if the checklist seemed satisfied?', 'This module depends entirely on the stability built in every module before it — it is not a technique that compensates for incomplete foundational work.', '2', 'enhanced', 't', '{"advanced": true, "source_basis": "manual", "source_chapters": [10], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('7df4951b-83b8-4241-b76b-1dfd57e51dc1', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '8', '6', 'Correspondence Systems', 'Zodiac Correspondence Sequence', 'This system applies the traditional correspondence between the twelve zodiac signs and specific body regions, treated in a fixed sequence from Aries through Pisces, generally after foundational energetic work is already complete.', '["Aries-to-Pisces order", "body correspondences", "sequence consistency", "final reassessment"]'::jsonb, 'Fluency moving through the full twelve-sign sequence in order, integrated with rather than separate from the rest of the treatment system.', 'The zodiac massage system applies the traditional correspondence between the twelve zodiac signs and specific regions of the human body. Treatment follows a structured sequence, with each sign representing a particular energetic relationship within the body. The purpose is to harmonize the organism through these correspondences while maintaining balanced energetic circulation. This method is generally performed after the foundational energetic work has been completed.

Aries — Associated with the head. Treatment focuses on restoring energetic balance in the cranial region.
Taurus — Associated with the neck and throat. Attention is directed toward the cervical area and energetic expression.
Gemini — Associated with the shoulders, arms, and hands. Treatment seeks to harmonize energetic circulation through the upper limbs.
Cancer — Associated with the chest. Work emphasizes balanced energetic movement through the thoracic region.
Leo — Associated with the heart and upper back. Treatment supports balanced energetic activity in the center of the body.
Virgo — Associated with the abdomen and digestive region. The objective is to harmonize energetic circulation through the central abdominal area.
Libra — Associated with the lumbar region and kidneys. Treatment emphasizes equilibrium and energetic symmetry.
Scorpio — Associated with the pelvic region. Attention is directed toward restoring balanced energetic activity in the lower body.
Sagittarius — Associated with the hips and thighs. Treatment supports energetic movement through the upper legs.
Capricorn — Associated with the knees. The objective is to restore smooth energetic circulation through the joints.
Aquarius — Associated with the lower legs and ankles. Treatment encourages balanced energetic flow throughout the lower limbs.
Pisces — Associated with the feet. The sequence concludes by harmonizing the body''s energetic foundation.

Treatment Sequence & Completion
A complete zodiac massage follows the natural order from Aries through Pisces. Maintaining this sequence establishes consistency throughout the treatment. Zodiac massage may be combined with chakra, nadi, kundalini, and five-element work; the practitioner should always preserve the overall energetic balance established during earlier stages. At the conclusion, reassess the client''s energetic condition, confirm balanced circulation throughout the body, allow the client time to rest, and record observations for future comparison.', 'Name each region''s corresponding sign aloud or silently as you move through the sequence, to keep the correspondence, not just the anatomy, in mind.', 'Combine a zodiac sequence with chakra or nadi work in one session, and note where the two systems'' regions overlapped or reinforced each other.', 'Did any single sign''s region show a disturbance disproportionate to the rest of the sequence, and did that match anything from your earlier assessment?', 'This sequence is designed to be combined with, not substituted for, the chakra, nadi, and kundalini work already covered — always preserve the balance those stages established.', '2', 'standard', 't', '{"source_basis": "manual", "source_chapters": [11], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('e1a844d2-1a9b-4e58-b299-9457a4558760', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '9', '6', 'Correspondence Systems', 'Five-Element Balancing', 'The five-element system — earth, water, fire, air, and ether — organizes treatment around five fundamental qualities of energetic function, with health depending on their balanced interaction rather than any one element''s dominance.', '["Earth stability", "Water flow", "Fire vitality", "Air distribution", "Ether integration"]'::jsonb, 'The ability to assess and treat all five elements as one balanced, interdependent system.', 'The five-element massage system organizes treatment according to the five fundamental elements: earth, water, fire, air, and ether. Each element represents a particular quality of energetic function. The practitioner evaluates the relative balance of these elements and applies treatment to restore harmony throughout the energetic system. No single element is considered superior; health depends upon their balanced interaction. This method is performed after the foundational work on the chakras, nadis, kundalini, and zodiac correspondences.

Earth
Characteristics: Stability · Structure · Physical strength · Grounding · Endurance.
Treatment goal: Restore stability and strengthen the body''s energetic foundation. Observe areas showing weakness or poor energetic support.

Water
Characteristics: Movement · Adaptability · Nourishment · Internal balance.
Treatment goal: Encourage smooth energetic circulation and restore fluid energetic movement throughout the body.

Fire
Characteristics: Vitality · Transformation · Activity · Internal warmth.
Treatment goal: Strengthen deficient energetic activity while avoiding excessive stimulation. Treatment should encourage balanced vitality rather than excess.

Air
Characteristics: Movement · Communication · Flexibility · Distribution.
Treatment goal: Improve energetic communication between different regions of the body and restore even circulation.

Ether
Characteristics: Integration · Space · Unity · Higher energetic organization.
Treatment goal: Unify the entire energetic system and integrate the effects of treatment. Ether concludes the elemental sequence.

Elemental Harmonization
After each element has been treated individually, reassess their relationship as a whole: overall energetic balance, symmetry, continuity of energetic flow, areas requiring additional correction, and integration with the chakra system. The objective is not to strengthen one element independently but to establish harmony among all five.', 'Before beginning, identify which single element seems most obviously deficient or excessive in this client — treat that imbalance in view throughout, not just the elements in fixed order.', 'Perform a full five-element sequence and integrate it explicitly with the already-balanced chakra system, checking that ether''s unifying work actually connects back to it.', 'Which element was easiest for you to sense and work with, and which was hardest — what might that say about your own energetic tendencies as a practitioner?', 'This method is applied after foundational chakra, nadi, kundalini, and zodiac work — it integrates and completes rather than replaces what came before.', '3', 'standard', 't', '{"source_basis": "manual", "source_chapters": [12], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('799cee1a-2ff3-4829-901a-43d9a1d483d9', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '10', '7', 'Spiritual & Protocol Integration', 'Prayer, Mantra & Symbolic Practice', 'This module adds the mental, verbal, and symbolic dimension of practice — prayer, mantra, and visualization — as a complement to manual technique, not a replacement for it.', '["mental preparation", "prayer", "mantra", "symbolic visualization", "steady breathing", "observation"]'::jsonb, 'Prayer, mantra, and visualization used consistently and usefully alongside manual technique, without ever substituting for direct observation.', 'This section combines the mental, verbal, and symbolic aspects of energetic practice with massage. These methods are complementary to manual techniques rather than replacements for them. The practitioner''s attention, intention, and disciplined mental focus are integral to the treatment process.

Mental Preparation
Before beginning treatment: calm the mind, release distracting thoughts, establish a clear therapeutic intention, maintain steady breathing, and focus attention on the client and the treatment process. Mental distraction should be minimized throughout the session.

Prayer
Prayer is used as a method of preparing the practitioner and maintaining focused intention during treatment. Its purpose is to establish inner calm, strengthen concentration, support disciplined practice, and encourage respect for the therapeutic process. Prayer should never interrupt the rhythm of treatment.

Mantras
Mantras assist concentration and maintain a consistent mental state during energetic work. They may be used before treatment, during work with specific energetic centers, during harmonization, and at the conclusion of treatment. The practitioner should apply them consistently and with full attention.

Symbolic Visualization
Visualization is used to maintain awareness of energetic movement and the relationship between different parts of the energetic system. The practitioner maintains a clear mental image of the energetic channels, the chakras, the movement of energy, and overall energetic balance. Visualization supports concentration but does not replace careful observation.

Integration with Massage
Prayer, mantra, and visualization are combined with manual techniques rather than practiced independently. During treatment the practitioner maintains continuous awareness, steady breathing, relaxed posture, gentle hand contact, and consistent intention. After treatment: gradually conclude manual work, allow several moments of stillness, reassess the client''s energetic condition, and end the session calmly and deliberately, giving the client sufficient time to return gradually to normal awareness before standing.', 'Choose one mantra and use it consistently at the same point in every session, the beginning or the conclusion, until it becomes an automatic anchor for your own focus.', 'Run one full session using prayer, mantra, and visualization together with your manual technique, and afterward assess honestly whether they supported your concentration or became a distraction from direct observation.', 'Where did visualization sharpen your actual perception of the client''s energy, and where did it start to substitute for perception you had not actually confirmed?', 'These practices are woven through every technique already covered, not a separate stage — revisit earlier modules with this mental discipline added, rather than treating it as new content layered on top.', '2', 'standard', 't', '{"source_basis": "manual", "source_chapters": [13], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

INSERT INTO training_branch_modules (id, branch_id, module_number, phase_number, phase_title, title, summary, focus, outcome, primary_practice, micro_practice, field_assignment, journal_prompt, integration_practice, minimum_repetitions, safety_level, is_published, metadata)
VALUES ('7c417eee-0b1a-4c28-a966-6ec004f2d5db', '31f144d6-7c9b-4fa0-b066-51594c4ae349', '11', '7', 'Spiritual & Protocol Integration', 'Complete Treatment Protocols & Practitioner Integration', 'The complete protocol integrates every method from the previous ten modules into one structured session — assessment, chakra harmonization, nadi balancing, kundalini integration, zodiac and five-element work as indicated, and final harmonization — with no stage skipped.', '["Basic Harmonization", "Chakra Protocol", "Nadi Protocol", "Kundalini Protocol", "Zodiac Protocol", "Five-Element Protocol", "final harmonization", "records"]'::jsonb, 'The ability to run a complete, properly sequenced treatment session independently, integrating every technique from this branch into one coherent practice.', 'The complete treatment protocol integrates the methods presented in the previous chapters into one structured session. Each stage builds upon the previous one, beginning with assessment and concluding with final energetic harmonization. The practitioner should avoid skipping stages, as each contributes to the stability of the overall treatment.

Standard Session Structure
Preparation
Energetic diagnosis
Chakra harmonization
Nadi balancing
Kundalini integration
Zodiac treatment (when indicated)
Five-element balancing (when indicated)
Final harmonization
Closing assessment

Protocol I — Basic Harmonization
Purpose: general energetic balancing, recommended for routine maintenance. Sequence: prepare practitioner and client; perform energetic assessment; examine the spine; assess the chakras; correct major energetic imbalances; reassess; complete treatment.

Protocol II — Chakra Harmonization
Focused primarily on the seven primary energy centers. Sequence: initial diagnosis, then Root, Sacral, Solar Plexus, Heart, Throat, Third Eye, and Crown in order, followed by final balancing.

Protocol III — Nadi Harmonization
For imbalance centered on the body''s primary channels. Sequence: reassess the chakras; treat Sushumna; treat Ida; treat Pingala; balance the three channels; perform final assessment.

Protocol IV — Kundalini Integration
Follows successful chakra and nadi harmonization. Sequence: confirm readiness; review previous energetic corrections; perform kundalini treatment; integrate with the chakras; reassess energetic balance; complete the session.

Protocol V — Zodiac Massage
Treat each correspondence in order — Aries, Taurus, Gemini, Cancer, Leo, Virgo, Libra, Scorpio, Sagittarius, Capricorn, Aquarius, Pisces — and complete with a full energetic reassessment.

Protocol VI — Five-Element Treatment
Treat Earth, Water, Fire, Air, and Ether in sequence. After each element has been addressed, perform an overall elemental balancing before concluding treatment.

Final Harmonization
The closing phase combines all previous work. The practitioner reviews the energetic condition of the chakras, confirms balance between Ida and Pingala, reassesses the central channel, confirms even energetic circulation throughout the body, and resolves any remaining areas of imbalance. No new corrective techniques should be introduced during this stage.

Completion of Treatment
Before concluding: allow the client to remain resting, reassess the overall energetic state, record observations, note recommendations for future sessions, and conclude calmly and deliberately. Every treatment should end with confirmation that the energetic system is more balanced than at the beginning of the session.', 'Before a full session, recite the nine-stage sequence from memory, without notes, until it comes as naturally as any other practiced skill.', 'Run one complete session end to end using the full protocol, then write down which stage felt least secure — that is where further practice belongs, not the stages that already feel solid.', 'Looking back across all eleven modules, which single skill changed the most from where you started?', 'This module is the synthesis of the entire branch — it does not introduce new technique, only the discipline of applying everything already learned in the right order, every time.', '3', 'standard', 't', '{"capstone": true, "source_basis": "manual", "source_chapters": [14], "training_expansion": true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, summary=EXCLUDED.summary, focus=EXCLUDED.focus, outcome=EXCLUDED.outcome, primary_practice=EXCLUDED.primary_practice, micro_practice=EXCLUDED.micro_practice, field_assignment=EXCLUDED.field_assignment, journal_prompt=EXCLUDED.journal_prompt, integration_practice=EXCLUDED.integration_practice, minimum_repetitions=EXCLUDED.minimum_repetitions, safety_level=EXCLUDED.safety_level, is_published=EXCLUDED.is_published, metadata=EXCLUDED.metadata;

